### PR TITLE
hide hints in the map

### PR DESCRIPTION
**Pull request by lifers**

### CODE REVIEW

**Review by connorsicheri — COMMENTED** [review]
Looks Great. Merge whenever ready

**Comment by lifers** [comment]
Great, waiting for approval

**Review by IbrahimShanqiti — COMMENTED** [review]
Good work fixing the issue of hints and the map revealing where each country is. Relevant issue is now also resolved.

**Review by connorsicheri — APPROVED** [review]
Merge conflict resolved

**Pull request merged**
