### PR TITLE
Connor

### PR DESCRIPTION
**Pull request by connorsicheri**
Tentative finish of the "interactor" for the Answer Question Use Case.

### CODE REVIEW

**Comment by IbrahimShanqiti** [comment]
From what I can tell, this follows the clean architecture specifications necessary for this project, and does what it needs to do.

**Comment by lifers** [comment]
I think we should add some Javadoc before merging this into main, otherwise good code. Tests can follow after the view is usable I think.

**Comment by YoshikuYuu** [comment]
It seems to follow CA pretty nicely but it's not really linked up to the interface adapters yet. Also, we should probably write some tests to check that the code actually works before we merge it into main. The code looks organized and clean so far though, so good job!

**Comment by YoshikuYuu** [comment]
Closed since the use case is not complete.

**Pull request closed without merging**
